# Readme

# Imports

In [8]:
import sys
import time
import pandas as pd
import requests
from bs4 import BeautifulSoup

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
pd.set_option("display.max_colwidth", None)

# find divs (run once)
go through each url and find div class of main text. save div class to new csv file as "../data/media_body_divs.csv"

In [13]:

"""
Read unique_media_urls.csv, fetch one representative article per media outlet,
and detect the CSS selector (div.class) of the main article-body container.

The heuristic: among all <div> elements, pick the one whose *direct* <p>
children contain the most combined text. That div is almost always the
article body. Fall back to id-based selector if the div has no class.
"""


df = pd.read_csv("../data/unique_media_urls.csv")
df

'\nRead unique_media_urls.csv, fetch one representative article per media outlet,\nand detect the CSS selector (div.class) of the main article-body container.\n\nThe heuristic: among all <div> elements, pick the one whose *direct* <p>\nchildren contain the most combined text. That div is almost always the\narticle body. Fall back to id-based selector if the div has no class.\n'

,media_name,url
0,chinanews.com,http://www.chinanews.com/mil/2018/06-30/8552129.shtml
1,xinhuanet.com,http://www.xinhuanet.com/politics/2018-06/30/c_1123059151.htm
2,voc.com.cn,http://hunan.voc.com.cn/article/201806/201806301027556256.html
3,people.com.cn,http://sports.people.com.cn/worldcup2018/n1/2018/0630/c418684-30097237.html
4,ce.cn,http://ce.cn/xwzx/gnsz/gdxw/201806/30/t20180630_29580863.shtml
5,huanqiu.com,http://world.huanqiu.com/exclusive/2018-07/12394543.html
6,lzbs.com.cn,http://www.lzbs.com.cn/ttnews/2018-07/02/content_4398536.htm
7,01ny.cn,http://news.01ny.cn/2018/fazhizongheng_0713/967320.html
8,cnhubei.com,http://sports.cnhubei.com/2018/0716/399532.shtml
9,syd.com.cn,http://finance.syd.com.cn/system/2018/07/30/011670743.shtml
10,bjd.com.cn,http://www.bjd.com.cn/jx/jj/201807/31/t20180731_11089189.html
11,hangzhou.com.cn,http://jrsh.hangzhou.com.cn/sale/content/2018-07/31/content_7044621.htm
12,lyd.com.cn,http://news.lyd.com.cn/system/2018/08/04/030754430.shtml
13,southcn.com,http://dg.southcn.com/content/2018-09/02/content_183151592.htm
14,china.com.cn,http://news.china.com.cn/2018-10/07/content_65124244.htm
15,chinadaily.com.cn,http://cn.chinadaily.com.cn/2018-10/20/content_37108458.htm
16,xhby.net,http://js.xhby.net/system/2018/11/11/030894128.shtml
17,yangtse.com,http://www.yangtse.com/app/sports/2018-12-02/646598.html
18,cctv.com,http://m.news.cctv.com/2018/12/09/ARTIoDVB1tlTn90BksTTLs6S181209.shtml
19,gmw.cn,http://politics.gmw.cn/2018-12/09/content_32134461.htm
20,cet.com.cn,http://www.cet.com.cn/whpd/whrd/2146080.shtml
21,qstheory.cn,http://www.qstheory.cn/llwx/2019-01/26/c_1124045768.htm
22,zjol.com.cn,http://zjtyol.zjol.com.cn/tyjsb/201904/t20190416_9909567.shtml
23,cri.cn,http://sports.cri.cn/20190416/951a55e8-cb80-3804-4c38-c3dafd64ab79.html
24,ycwb.com,http://wap.ycwb.com/2019-04/19/content_30242800.htm
25,dzwww.com,https://www.dzwww.com/xinwen/guojixinwen/201904/t20190428_18666134.htm
26,rednet.cn,https://sports.rednet.cn/content/2019/02/06/4760145.html
27,qianlong.com,http://sports.qianlong.com/2019/0219/3119469.shtml
28,legaldaily.com.cn,http://www.legaldaily.com.cn/index/content/2019-02/27/content_7782565.htm
29,jcrb.com,http://news.jcrb.com/jxsw/201903/t20190302_1968982.html
30,timedg.com,http://www.timedg.com/sjb/p/20827660.html
31,xmnn.cn,https://news.xmnn.cn/xmnn/2019/05/03/100529757.shtml
32,jxnews.com.cn,http://news.jxnews.com.cn/system/2019/05/03/017482261.shtml
33,66wz.com,http://news.66wz.com/system/2019/05/12/105165588.shtml
34,qlwb.com.cn,http://www.qlwb.com.cn/2019/0520/1428950.shtml
35,yunnan.cn,http://yn.yunnan.cn/system/2019/05/21/030281888.shtml
36,nmgnews.com.cn,http://sports.nmgnews.com.cn/system/2019/06/03/012719877.shtml
37,cnnb.com.cn,http://news.cnnb.com.cn/system/2019/06/18/030060697.shtml
38,fynews.net,https://news.fynews.net/article-177378-1.html
39,cjn.cn,http://news.cjn.cn/gnxw/201907/t3434390.htm
40,eastday.com,http://sh.eastday.com/m/20190731/u1ai12717586.html
41,81.cn,http://www.81.cn/2019qglhzt/2019-03/07/content_9443911.htm

In [36]:
# functions

# mimic request from real browser (instead of python script)
HEADERS = {
    "User-Agent": ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                   "AppleWebKit/537.36 (KHTML, like Gecko) "
                   "Chrome/125.0 Safari/537.36")
}

def css_format_converter(tag):
    
    classx = tag.get("class")
    if classx:
        return f"{tag.name}." + ".".join(classx)
        
    idx = tag.get("id")
    if idx:
        return f"{tag.name}#" + idx

    # otherwise
    return tag.name


def find_textbody_tag(url):
    r = requests.get(url, headers=HEADERS, timeout=20)
    r.encoding = r.apparent_encoding or r.encoding
    soup = BeautifulSoup(r.text, "html.parser")


    # find tag that has the most number of <p> children == the main body tag.
    best_tag, best_len = None, 0
    for tag in soup.find_all(True):  # True matches any tag
        direct_p = tag.find_all("p", recursive=False)
        if not direct_p:
            continue
        text = "".join(p.get_text(strip=True) for p in direct_p) # join all text in the <p>s for counting
        if len(text) > best_len:
            best_len = len(text)
            best_tag = css_format_converter(tag)

    if best_tag is None:
        return None, 0
        
    return best_tag, best_len

In [46]:
rows = []
for i, r in df.iterrows():
    media, url = r["media_name"], r["url"]
    try:
        textbody_tag, textlen = find_textbody_tag(url)
        rows.append({
            "media_name": media,
            "url": url,
            "body_div": textbody_tag,
            "body_text_len": textlen,
            "error": None,
        })
        
        print(f"OK   {media:20s} -> {textbody_tag}  ({textlen} chars)")
    except Exception as e:
        rows.append({
            "media_name": media,
            "url": url,
            "body_div": None,
            "body_text_len": 0,
            "error": str(e),
        })
        print(f"FAIL {media:20s} -> {e}", file=sys.stderr)
    time.sleep(1)  # be polite

result = pd.DataFrame(rows)
result.to_csv("../data/results.csv", index=False)
result

OK   chinanews.com        -> div.left_zw  (2021 chars)
OK   xinhuanet.com        -> div#p-detail  (5503 chars)
OK   voc.com.cn           -> div#content  (606 chars)
OK   people.com.cn        -> div.rm_txt_con.cf  (2170 chars)

FAIL ce.cn                -> HTTPConnectionPool(host='ce.cn', port=80): Max retries exceeded with url: /xwzx/gnsz/gdxw/201806/30/t20180630_29580863.shtml (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x15ead0af0>, 'Connection to ce.cn timed out. (connect timeout=20)'))

OK   huanqiu.com          -> None  (0 chars)

FAIL lzbs.com.cn          -> HTTPConnectionPool(host='www.lzbs.com.cn', port=80): Max retries exceeded with url: /ttnews/2018-07/02/content_4398536.htm (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x15ead05a0>, 'Connection to www.lzbs.com.cn timed out. (connect timeout=20)'))

OK   01ny.cn              -> div.hide_me.P.H  (175 chars)

FAIL cnhubei.com          -> HTTPConnectionPool(host='sports.cnhubei.com', port=80): Max retries exceeded with url: /2018/0716/399532.shtml (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x15ead3680>: Failed to resolve 'sports.cnhubei.com' ([Errno 8] nodename nor servname provided, or not known)"))
FAIL syd.com.cn           -> HTTPConnectionPool(host='finance.syd.com.cn', port=80): Max retries exceeded with url: /system/2018/07/30/011670743.shtml (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x15ead0af0>: Failed to resolve 'finance.syd.com.cn' ([Errno 8] nodename nor servname provided, or not known)"))

OK   bjd.com.cn           -> div.bjd-not-found__con  (65 chars)
OK   hangzhou.com.cn      -> td.Dlife_bcolor02  (926 chars)
OK   lyd.com.cn           -> div.page-bottom-word  (102 chars)

FAIL southcn.com          -> HTTPConnectionPool(host='dg.southcn.com', port=80): Max retries exceeded with url: /content/2018-09/02/content_183151592.htm (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x15ead0af0>: Failed to resolve 'dg.southcn.com' ([Errno 8] nodename nor servname provided, or not known)"))

OK   china.com.cn         -> div.articleBody  (2814 chars)
OK   chinadaily.com.cn    -> div.article  (1081 chars)

FAIL xhby.net             -> HTTPConnectionPool(host='js.xhby.net', port=80): Max retries exceeded with url: /system/2018/11/11/030894128.shtml (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x15ead3240>: Failed to resolve 'js.xhby.net' ([Errno 8] nodename nor servname provided, or not known)"))

OK   yangtse.com          -> div.error-card  (28 chars)
OK   cctv.com             -> div.cnt_bd  (1405 chars)
OK   gmw.cn               -> None  (0 chars)

FAIL cet.com.cn           -> HTTPConnectionPool(host='www.cet.com.cn', port=80): Max retries exceeded with url: /whpd/whrd/2146080.shtml (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x15ead0d10>, 'Connection to www.cet.com.cn timed out. (connect timeout=20)'))

OK   qstheory.cn          -> div.highlight  (1658 chars)
OK   zjol.com.cn          -> div.contTxt  (5100 chars)
OK   cri.cn               -> div.abody  (4839 chars)
OK   ycwb.com             -> div.main_article  (6375 chars)
OK   dzwww.com            -> None  (0 chars)
OK   rednet.cn            -> section.f_right.detail_article_content  (3036 chars)
OK   qianlong.com         -> div.article-content  (1137 chars)
OK   legaldaily.com.cn    -> None  (0 chars)
OK   jcrb.com             -> None  (0 chars)

FAIL timedg.com           -> ('Connection broken: IncompleteRead(47479 bytes read, 1 more expected)', IncompleteRead(47479 bytes read, 1 more expected))

OK   xmnn.cn              -> div.m1  (14 chars)

FAIL jxnews.com.cn        -> HTTPSConnectionPool(host='news.jxnews.com.cn', port=443): Max retries exceeded with url: /system/2019/05/03/017482261.shtml (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] ssl/tls alert handshake failure (_ssl.c:1032)')))

OK   66wz.com             -> div#artibody  (11956 chars)
OK   qlwb.com.cn          -> None  (0 chars)
OK   yunnan.cn            -> div#layer216  (1283 chars)

FAIL nmgnews.com.cn       -> HTTPConnectionPool(host='sports.nmgnews.com.cn', port=80): Max retries exceeded with url: /system/2019/06/03/012719877.shtml (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x15ead05a0>: Failed to resolve 'sports.nmgnews.com.cn' ([Errno 8] nodename nor servname provided, or not known)"))

OK   cnnb.com.cn          -> None  (0 chars)
OK   fynews.net           -> body  (52 chars)
OK   cjn.cn               -> div.footer  (223 chars)
OK   eastday.com          -> None  (0 chars)
OK   81.cn                -> div.container  (5474 chars)

,media_name,url,body_div,body_text_len,error
0,chinanews.com,http://www.chinanews.com/mil/2018/06-30/8552129.shtml,div.left_zw,2021,None
1,xinhuanet.com,http://www.xinhuanet.com/politics/2018-06/30/c_1123059151.htm,div#p-detail,5503,None
2,voc.com.cn,http://hunan.voc.com.cn/article/201806/201806301027556256.html,div#content,606,None
3,people.com.cn,http://sports.people.com.cn/worldcup2018/n1/2018/0630/c418684-30097237.html,div.rm_txt_con.cf,2170,None
4,ce.cn,http://ce.cn/xwzx/gnsz/gdxw/201806/30/t20180630_29580863.shtml,None,0,"HTTPConnectionPool(host='ce.cn', port=80): Max retries exceeded with url: /xwzx/gnsz/gdxw/201806/30/t20180630_29580863.shtml (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x15ead0af0>, 'Connection to ce.cn timed out. (connect timeout=20)'))"
5,huanqiu.com,http://world.huanqiu.com/exclusive/2018-07/12394543.html,None,0,None
6,lzbs.com.cn,http://www.lzbs.com.cn/ttnews/2018-07/02/content_4398536.htm,None,0,"HTTPConnectionPool(host='www.lzbs.com.cn', port=80): Max retries exceeded with url: /ttnews/2018-07/02/content_4398536.htm (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x15ead05a0>, 'Connection to www.lzbs.com.cn timed out. (connect timeout=20)'))"
7,01ny.cn,http://news.01ny.cn/2018/fazhizongheng_0713/967320.html,div.hide_me.P.H,175,None
8,cnhubei.com,http://sports.cnhubei.com/2018/0716/399532.shtml,None,0,"HTTPConnectionPool(host='sports.cnhubei.com', port=80): Max retries exceeded with url: /2018/0716/399532.shtml (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x15ead3680>: Failed to resolve 'sports.cnhubei.com' ([Errno 8] nodename nor servname provided, or not known)""))"
9,syd.com.cn,http://finance.syd.com.cn/system/2018/07/30/011670743.shtml,None,0,"HTTPConnectionPool(host='finance.syd.com.cn', port=80): Max retries exceeded with url: /system/2018/07/30/011670743.shtml (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x15ead0af0>: Failed to resolve 'finance.syd.com.cn' ([Errno 8] nodename nor servname provided, or not known)""))"
10,bjd.com.cn,http://www.bjd.com.cn/jx/jj/201807/31/t20180731_11089189.html,div.bjd-not-found__con,65,None
11,hangzhou.com.cn,http://jrsh.hangzhou.com.cn/sale/content/2018-07/31/content_7044621.htm,td.Dlife_bcolor02,926,None
12,lyd.com.cn,http://news.lyd.com.cn/system/2018/08/04/030754430.shtml,div.page-bottom-word,102,None
13,southcn.com,http://dg.southcn.com/content/2018-09/02/content_183151592.htm,None,0,"HTTPConnectionPool(host='dg.southcn.com', port=80): Max retries exceeded with url: /content/2018-09/02/content_183151592.htm (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x15ead0af0>: Failed to resolve 'dg.southcn.com' ([Errno 8] nodename nor servname provided, or not known)""))"
14,china.com.cn,http://news.china.com.cn/2018-10/07/content_65124244.htm,div.articleBody,2814,None
15,chinadaily.com.cn,http://cn.chinadaily.com.cn/2018-10/20/content_37108458.htm,div.article,1081,None
16,xhby.net,http://js.xhby.net/system/2018/11/11/030894128.shtml,None,0,"HTTPConnectionPool(host='js.xhby.net', port=80): Max retries exceeded with url: /system/2018/11/11/030894128.shtml (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x15ead3240>: Failed to resolve 'js.xhby.net' ([Errno 8] nodename nor servname provided, or not known)""))"
17,yangtse.com,http://www.yangtse.com/app/sports/2018-12-02/646598.html,div.error-card,28,None
18,cctv.com,http://m.news.cctv.com/2018/12/09/ARTIoDVB1tlTn90BksTTLs6S181209.shtml,div.cnt_bd,1405,None
19,gmw.cn,http://politics.gmw.cn/2018-12/09/content_32134461.htm,None,0,None
20,cet.com.cn,http://www.cet.com.cn/whpd/whrd/2146080.shtml,None,0,"HTTPConnectionPool(host='www.cet.com.cn', port=80): Max retries exceeded with url: /whpd/whrd/2146080.shtml (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x15ead0d10>, 'Connection to www.cet.com.cn timed out. (connect timeout=20)'))"
21,qstheory.cn,http://www.qstheory.cn/llwx/2019-01/26/c_1124045768.htm,div.highlight,1658,None
22,zjol.com.cn,http://zjtyol.zjol.com.cn/tyjsb/201904/t20190416_9909567.shtml,div.contTxt,5100,None
23,cri.cn,http://sports.cri.cn/20190416/951a55e8-cb80-3804-4c38-c3dafd64ab79.html,div.abody,4839,None
24,ycwb.com,http://wap.ycwb.com/2019-04/19/content_30242800.htm,div.main_article,6375,None
25,dzwww.com,https://www.dzwww.com/xinwen/guojixinwen/201904/t20190428_18666134.htm,None,0,None
26,rednet.cn,https://sports.rednet.cn/content/2019/02/06/4760145.html,section.f_right.detail_article_content,3036,None
27,qianlong.com,http://sports.qianlong.com/2019/0219/3119469.shtml,div.article-content,1137,None
28,legaldaily.com.cn,http://www.legaldaily.com.cn/index/content/2019-02/27/content_7782565.htm,None,0,None
29,jcrb.com,http://news.jcrb.com/jxsw/201903/t20190302_1968982.html,None,0,None
30,timedg.com,http://www.timedg.com/sjb/p/20827660.html,None,0,"('Connection broken: IncompleteRead(47479 bytes read, 1 more expected)', IncompleteRead(47479 bytes read, 1 more expected))"
31,xmnn.cn,https://news.xmnn.cn/xmnn/2019/05/03/100529757.shtml,div.m1,14,None
32,jxnews.com.cn,http://news.jxnews.com.cn/system/2019/05/03/017482261.shtml,None,0,"HTTPSConnectionPool(host='news.jxnews.com.cn', port=443): Max retries exceeded with url: /system/2019/05/03/017482261.shtml (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] ssl/tls alert handshake failure (_ssl.c:1032)')))"
33,66wz.com,http://news.66wz.com/system/2019/05/12/105165588.shtml,div#artibody,11956,None
34,qlwb.com.cn,http://www.qlwb.com.cn/2019/0520/1428950.shtml,None,0,None
35,yunnan.cn,http://yn.yunnan.cn/system/2019/05/21/030281888.shtml,div#layer216,1283,None
36,nmgnews.com.cn,http://sports.nmgnews.com.cn/system/2019/06/03/012719877.shtml,None,0,"HTTPConnectionPool(host='sports.nmgnews.com.cn', port=80): Max retries exceeded with url: /system/2019/06/03/012719877.shtml (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x15ead05a0>: Failed to resolve 'sports.nmgnews.com.cn' ([Errno 8] nodename nor servname provided, or not known)""))"
37,cnnb.com.cn,http://news.cnnb.com.cn/system/2019/06/18/030060697.shtml,None,0,None
38,fynews.net,https://news.fynews.net/article-177378-1.html,body,52,None
39,cjn.cn,http://news.cjn.cn/gnxw/201907/t3434390.htm,div.footer,223,None
40,eastday.com,http://sh.eastday.com/m/20190731/u1ai12717586.html,None,0,None
41,81.cn,http://www.81.cn/2019qglhzt/2019-03/07/content_9443911.htm,div.container,5474,None

In [53]:
result2 = result[ ~result.body_div.isna()][["media_name", "body_div"]]
result2.to_csv("../data/media_textbody_tags.csv")
result2

           media_name                                body_div
0       chinanews.com                             div.left_zw
1       xinhuanet.com                            div#p-detail
2          voc.com.cn                             div#content
3       people.com.cn                       div.rm_txt_con.cf
7             01ny.cn                         div.hide_me.P.H
10         bjd.com.cn                  div.bjd-not-found__con
11    hangzhou.com.cn                       td.Dlife_bcolor02
12         lyd.com.cn                    div.page-bottom-word
14       china.com.cn                         div.articleBody
15  chinadaily.com.cn                             div.article
17        yangtse.com                          div.error-card
18           cctv.com                              div.cnt_bd
21        qstheory.cn                           div.highlight
22        zjol.com.cn                             div.contTxt
23             cri.cn                               div.abody
24           ycwb.com                        div.main_article
26          rednet.cn  section.f_right.detail_article_content
27       qianlong.com                     div.article-content
31            xmnn.cn                                  div.m1
33           66wz.com                            div#artibody
35          yunnan.cn                            div#layer216
38         fynews.net                                    body
39             cjn.cn                              div.footer
41              81.cn                           div.container

# /////// fix NaNs

some links do not work: find new urls from the same media company

In [5]:
df = pd.read_csv("../data/media_body_divs.csv")
df

,media_name,url,body_div,body_text_len,error
0,chinanews.com,http://www.chinanews.com/mil/2018/06-30/855212...,div.left_zw,2021,NaN
1,xinhuanet.com,http://www.xinhuanet.com/politics/2018-06/30/c...,div#p-detail,5503,NaN
2,voc.com.cn,http://hunan.voc.com.cn/article/201806/2018063...,div#content,606,NaN
3,people.com.cn,http://sports.people.com.cn/worldcup2018/n1/20...,div.rm_txt_con.cf,2170,NaN
4,ce.cn,http://ce.cn/xwzx/gnsz/gdxw/201806/30/t2018063...,NaN,0,"HTTPConnectionPool(host='ce.cn', port=80): Max..."
5,huanqiu.com,http://world.huanqiu.com/exclusive/2018-07/123...,NaN,0,NaN
6,lzbs.com.cn,http://www.lzbs.com.cn/ttnews/2018-07/02/conte...,NaN,0,"HTTPConnectionPool(host='www.lzbs.com.cn', por..."
7,01ny.cn,http://news.01ny.cn/2018/fazhizongheng_0713/96...,div.hide_me.P.H,175,NaN
8,cnhubei.com,http://sports.cnhubei.com/2018/0716/399532.shtml,NaN,0,"HTTPConnectionPool(host='sports.cnhubei.com', ..."
9,syd.com.cn,http://finance.syd.com.cn/system/2018/07/30/01...,NaN,0,"HTTPConnectionPool(host='finance.syd.com.cn', ..."
10,bjd.com.cn,http://www.bjd.com.cn/jx/jj/201807/31/t2018073...,div.bjd-not-found__con,65,NaN
11,hangzhou.com.cn,http://jrsh.hangzhou.com.cn/sale/content/2018-...,div (no class/id),102,NaN
12,lyd.com.cn,http://news.lyd.com.cn/system/2018/08/04/03075...,div.page-bottom-word,101,NaN
13,southcn.com,http://dg.southcn.com/content/2018-09/02/conte...,NaN,0,"HTTPConnectionPool(host='dg.southcn.com', port..."
14,china.com.cn,http://news.china.com.cn/2018-10/07/content_65...,div.articleBody,2814,NaN
15,chinadaily.com.cn,http://cn.chinadaily.com.cn/2018-10/20/content...,div.article,1081,NaN
16,xhby.net,http://js.xhby.net/system/2018/11/11/030894128...,NaN,0,"HTTPConnectionPool(host='js.xhby.net', port=80..."
17,yangtse.com,http://www.yangtse.com/app/sports/2018-12-02/6...,div.error-card,28,NaN
18,cctv.com,http://m.news.cctv.com/2018/12/09/ARTIoDVB1tlT...,div.cnt_bd,1405,NaN
19,gmw.cn,http://politics.gmw.cn/2018-12/09/content_3213...,NaN,0,NaN
20,cet.com.cn,http://www.cet.com.cn/whpd/whrd/2146080.shtml,NaN,0,"HTTPConnectionPool(host='www.cet.com.cn', port..."
21,qstheory.cn,http://www.qstheory.cn/llwx/2019-01/26/c_11240...,div.highlight,1658,NaN
22,zjol.com.cn,http://zjtyol.zjol.com.cn/tyjsb/201904/t201904...,div.contTxt,5100,NaN
23,cri.cn,http://sports.cri.cn/20190416/951a55e8-cb80-38...,div.abody,4839,NaN
24,ycwb.com,http://wap.ycwb.com/2019-04/19/content_3024280...,NaN,0,NaN
25,dzwww.com,https://www.dzwww.com/xinwen/guojixinwen/20190...,NaN,0,NaN
26,rednet.cn,https://sports.rednet.cn/content/2019/02/06/47...,div.readnex_detail,5,NaN
27,qianlong.com,http://sports.qianlong.com/2019/0219/3119469.s...,div.article-content,1137,NaN
28,legaldaily.com.cn,http://www.legaldaily.com.cn/index/content/201...,NaN,0,NaN
29,jcrb.com,http://news.jcrb.com/jxsw/201903/t20190302_196...,NaN,0,NaN
30,timedg.com,http://www.timedg.com/sjb/p/20827660.html,NaN,0,"HTTPConnectionPool(host='www.timedg.com', port..."
31,xmnn.cn,https://news.xmnn.cn/xmnn/2019/05/03/100529757...,div.m1,14,NaN
32,jxnews.com.cn,http://news.jxnews.com.cn/system/2019/05/03/01...,NaN,0,"HTTPSConnectionPool(host='news.jxnews.com.cn',..."
33,66wz.com,http://news.66wz.com/system/2019/05/12/1051655...,div#artibody,11956,NaN
34,qlwb.com.cn,http://www.qlwb.com.cn/2019/0520/1428950.shtml,NaN,0,NaN
35,yunnan.cn,http://yn.yunnan.cn/system/2019/05/21/03028188...,div#layer216,1283,NaN
36,nmgnews.com.cn,http://sports.nmgnews.com.cn/system/2019/06/03...,NaN,0,HTTPConnectionPool(host='sports.nmgnews.com.cn...
37,cnnb.com.cn,http://news.cnnb.com.cn/system/2019/06/18/0300...,NaN,0,NaN
38,fynews.net,https://news.fynews.net/article-177378-1.html,NaN,0,NaN
39,cjn.cn,http://news.cjn.cn/gnxw/201907/t3434390.htm,div (no class/id),224,NaN
40,eastday.com,http://sh.eastday.com/m/20190731/u1ai12717586....,NaN,0,NaN
41,81.cn,http://www.81.cn/2019qglhzt/2019-03/07/content...,div.container,5474,NaN

In [9]:
df.iloc[11]

media_name                                                               hangzhou.com.cn
url              http://jrsh.hangzhou.com.cn/sale/content/2018-07/31/content_7044621.htm
body_div                                                               div (no class/id)
body_text_len                                                                        102
error                                                                                NaN
Name: 11, dtype: object