# Readme

# Imports

In [1]:
import pandas as pd
import os # for csv export

# for url html content parsing
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager
import time

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [4]:
df = pd.read_csv("../data/16-19_test.csv")

print(f"Loaded {len(df)} cases")
df.head()

Loaded 2488 cases

,id,indexed_date,language,media_name,media_url,publish_date,title,url
0,d0cb0ceda597ae6eb3e5c7e013d3a2276b9f24cabec598...,2025-07-24 02:06:58.254299+00:00,zh,chinanews.com,chinanews.com,2018-06-30,乘火车出行，“军人依法优先”政策有哪些？-中新网,http://www.chinanews.com/mil/2018/06-30/855212...
1,42ade47c5a72eee37d476c3b8252d60ebdab2e0e4f61dd...,2025-07-24 01:55:34.596230+00:00,zh,xinhuanet.com,xinhuanet.com,2018-06-30,长汀：客家祠堂里永传的“星火”-新华网,http://www.xinhuanet.com/politics/2018-06/30/c...
2,23e96912bbb5d8b168cbe391102387d3d5d31f88b510dc...,2025-07-24 01:55:34.190754+00:00,zh,xinhuanet.com,xinhuanet.com,2018-06-30,乘火车出行，“军人依法优先”政策有哪些？-新华网,http://www.xinhuanet.com/politics/2018-06/30/c...
3,7778c2031b728d74af28e40d0cdcf400d6011f6acf61f9...,2025-07-24 01:53:56.315790+00:00,zh,voc.com.cn,voc.com.cn,2018-06-30,47年党龄老党员的心愿――“交最后一次党费”,http://hunan.voc.com.cn/article/201806/2018063...
4,e81d0152513ec6b05bbd320a05283df504e6a4f56dbe10...,2025-07-24 01:52:19.195323+00:00,zh,people.com.cn,people.com.cn,2018-06-30,比球技，更要比文采?--体育--人民网,http://sports.people.com.cn/worldcup2018/n1/20...

2488

In [6]:
# keep only relevant data.
df_pretty = df[ ["title", "publish_date", "media_name", "url"] ].copy()
df_pretty.head()

,title,publish_date,media_name,url
0,乘火车出行，“军人依法优先”政策有哪些？-中新网,2018-06-30,chinanews.com,http://www.chinanews.com/mil/2018/06-30/855212...
1,长汀：客家祠堂里永传的“星火”-新华网,2018-06-30,xinhuanet.com,http://www.xinhuanet.com/politics/2018-06/30/c...
2,乘火车出行，“军人依法优先”政策有哪些？-新华网,2018-06-30,xinhuanet.com,http://www.xinhuanet.com/politics/2018-06/30/c...
3,47年党龄老党员的心愿――“交最后一次党费”,2018-06-30,voc.com.cn,http://hunan.voc.com.cn/article/201806/2018063...
4,比球技，更要比文采?--体育--人民网,2018-06-30,people.com.cn,http://sports.people.com.cn/worldcup2018/n1/20...

# Prep Data for Media Textbody Identification

get one url per media outlet

In [7]:
df_pretty.media_name.unique()
f"number of unique medias is {len(df_pretty.media_name.unique())}"

array(['chinanews.com', 'xinhuanet.com', 'voc.com.cn', 'people.com.cn',
       'ce.cn', 'huanqiu.com', 'lzbs.com.cn', '01ny.cn', 'cnhubei.com',
       'syd.com.cn', 'bjd.com.cn', 'hangzhou.com.cn', 'lyd.com.cn',
       'southcn.com', 'china.com.cn', 'chinadaily.com.cn', 'xhby.net',
       'yangtse.com', 'cctv.com', 'gmw.cn', 'cet.com.cn', 'qstheory.cn',
       'zjol.com.cn', 'cri.cn', 'ycwb.com', 'dzwww.com', 'rednet.cn',
       'qianlong.com', 'legaldaily.com.cn', 'jcrb.com', 'timedg.com',
       'xmnn.cn', 'jxnews.com.cn', '66wz.com', 'qlwb.com.cn', 'yunnan.cn',
       'nmgnews.com.cn', 'cnnb.com.cn', 'fynews.net', 'cjn.cn',
       'eastday.com', '81.cn'], dtype=object)

'number of unique medias is 42'

In [12]:
# create new df that only keeps one sample url per media compnay.
    
df_unique_media_urls = df_pretty.drop_duplicates(subset = "media_name")[["media_name", "url"]].reset_index(drop = True) # erases original index number
df_unique_media_urls

           media_name                                                url
0       chinanews.com  http://www.chinanews.com/mil/2018/06-30/855212...
1       xinhuanet.com  http://www.xinhuanet.com/politics/2018-06/30/c...
2          voc.com.cn  http://hunan.voc.com.cn/article/201806/2018063...
3       people.com.cn  http://sports.people.com.cn/worldcup2018/n1/20...
4               ce.cn  http://ce.cn/xwzx/gnsz/gdxw/201806/30/t2018063...
5         huanqiu.com  http://world.huanqiu.com/exclusive/2018-07/123...
6         lzbs.com.cn  http://www.lzbs.com.cn/ttnews/2018-07/02/conte...
7             01ny.cn  http://news.01ny.cn/2018/fazhizongheng_0713/96...
8         cnhubei.com   http://sports.cnhubei.com/2018/0716/399532.shtml
9          syd.com.cn  http://finance.syd.com.cn/system/2018/07/30/01...
10         bjd.com.cn  http://www.bjd.com.cn/jx/jj/201807/31/t2018073...
11    hangzhou.com.cn  http://jrsh.hangzhou.com.cn/sale/content/2018-...
12         lyd.com.cn  http://news.lyd.com.cn/system/2018/08/04/03075...
13        southcn.com  http://dg.southcn.com/content/2018-09/02/conte...
14       china.com.cn  http://news.china.com.cn/2018-10/07/content_65...
15  chinadaily.com.cn  http://cn.chinadaily.com.cn/2018-10/20/content...
16           xhby.net  http://js.xhby.net/system/2018/11/11/030894128...
17        yangtse.com  http://www.yangtse.com/app/sports/2018-12-02/6...
18           cctv.com  http://m.news.cctv.com/2018/12/09/ARTIoDVB1tlT...
19             gmw.cn  http://politics.gmw.cn/2018-12/09/content_3213...
20         cet.com.cn      http://www.cet.com.cn/whpd/whrd/2146080.shtml
21        qstheory.cn  http://www.qstheory.cn/llwx/2019-01/26/c_11240...
22        zjol.com.cn  http://zjtyol.zjol.com.cn/tyjsb/201904/t201904...
23             cri.cn  http://sports.cri.cn/20190416/951a55e8-cb80-38...
24           ycwb.com  http://wap.ycwb.com/2019-04/19/content_3024280...
25          dzwww.com  https://www.dzwww.com/xinwen/guojixinwen/20190...
26          rednet.cn  https://sports.rednet.cn/content/2019/02/06/47...
27       qianlong.com  http://sports.qianlong.com/2019/0219/3119469.s...
28  legaldaily.com.cn  http://www.legaldaily.com.cn/index/content/201...
29           jcrb.com  http://news.jcrb.com/jxsw/201903/t20190302_196...
30         timedg.com          http://www.timedg.com/sjb/p/20827660.html
31            xmnn.cn  https://news.xmnn.cn/xmnn/2019/05/03/100529757...
32      jxnews.com.cn  http://news.jxnews.com.cn/system/2019/05/03/01...
33           66wz.com  http://news.66wz.com/system/2019/05/12/1051655...
34        qlwb.com.cn     http://www.qlwb.com.cn/2019/0520/1428950.shtml
35          yunnan.cn  http://yn.yunnan.cn/system/2019/05/21/03028188...
36     nmgnews.com.cn  http://sports.nmgnews.com.cn/system/2019/06/03...
37        cnnb.com.cn  http://news.cnnb.com.cn/system/2019/06/18/0300...
38         fynews.net      https://news.fynews.net/article-177378-1.html
39             cjn.cn        http://news.cjn.cn/gnxw/201907/t3434390.htm
40        eastday.com  http://sh.eastday.com/m/20190731/u1ai12717586....
41              81.cn  http://www.81.cn/2019qglhzt/2019-03/07/content...

In [21]:
# check if result df contains the same number of media outlets as the original df.
df_unique_media_urls.shape[0] == df_pretty.media_name.unique().shape[0]

True

In [25]:
# save csv to processing in get_textbody_div.ipynb

df_unique_media_urls.to_csv("../data/unique_media_urls.csv", index = False)
print(f"output CSV file saved to {os.getcwd()}")

output CSV file saved to /Users/wyx/Desktop/26X/code

# Filter
visit each url using the "media_body_tags.csv".
check that media content must contain keyword 退役运动员

In [10]:
KEYWORD = "退役运动员"
df_checker = pd.read_csv("../data/media_textbody_tags.csv", index_col = 0) # designate column 0 as index. otherwise pandas treats it as a variable column.
df_checker

           media_name                                body_div
0       chinanews.com                             div.left_zw
1       xinhuanet.com                            div#p-detail
2          voc.com.cn                             div#content
3       people.com.cn                       div.rm_txt_con.cf
7             01ny.cn                         div.hide_me.P.H
10         bjd.com.cn                  div.bjd-not-found__con
11    hangzhou.com.cn                       td.Dlife_bcolor02
12         lyd.com.cn                    div.page-bottom-word
14       china.com.cn                         div.articleBody
15  chinadaily.com.cn                             div.article
17        yangtse.com                          div.error-card
18           cctv.com                              div.cnt_bd
21        qstheory.cn                           div.highlight
22        zjol.com.cn                             div.contTxt
23             cri.cn                               div.abody
24           ycwb.com                        div.main_article
26          rednet.cn  section.f_right.detail_article_content
27       qianlong.com                     div.article-content
31            xmnn.cn                                  div.m1
33           66wz.com                            div#artibody
35          yunnan.cn                            div#layer216
38         fynews.net                                    body
39             cjn.cn                              div.footer
41              81.cn                           div.container

In [11]:
# test the formula that gets the correct textbody tag according to the given url's media

for url in df.loc[:2, "url"]:
    match = df_checker[ df_checker.media_name.apply(lambda name: name in url) ].body_div.values
    print(match)

['div.left_zw']
['div#p-detail']
['div#p-detail']

In [23]:
# df_goodmedia: filter df_pretty so that it only contains urls from media sources with identified textbody tag. 

df_goodmedia = df_pretty[
    df_pretty.apply(lambda r: df_checker.media_name.apply(lambda name: name in r.url).any(), # returns true if any match is found.
                    axis = 1)].copy()

df_goodmedia.shape[0]
df_goodmedia.sample(5)

2340

,title,publish_date,media_name,url
549,女子链球再度摘金夺银&nbsp;罗娜、王峥扛起大旗,2018-08-25,01ny.cn,http://news.01ny.cn/2018/tiyuxinwen_0825/99432...
883,株洲市荷塘区打造“复转军人之家”营造军人社会尊崇氛围-新华网,2018-11-06,xinhuanet.com,http://www.xinhuanet.com/local/2018-11/06/c_12...
1572,跳“空中芭蕾”的中国女孩-新华网,2019-01-04,xinhuanet.com,http://www.xinhuanet.com/local/2019-01/04/c_11...
2287,洛阳市委十一届十次全会精神在全市各地持续引发强烈反响,2019-06-07,lyd.com.cn,http://news.lyd.com.cn/system/2019/06/07/03135...
2167,湖南开展“洞庭风雷”专项行动守护河湖安澜,2019-04-09,voc.com.cn,http://hnrb.voc.com.cn/article/201904/20190409...

In [93]:
# RUN all urls and check textbody for KEYWORD. saving result to keyword_check = []

def make_driver():
    options = Options()
    options.add_argument("--headless=new")
    options.add_argument("--no-sandbox")
    options.add_argument("--disable-dev-shm-usage")
    options.add_argument("--disable-gpu")
    options.add_argument("user-agent=Mozilla/5.0")
    service = Service(ChromeDriverManager().install())
    return webdriver.Chrome(service=service, options=options)

def contains_keyword(driver, url):
    try:
        driver.get(url)
        time.sleep(1)

        textbody_tag = df_checker[ df_checker.media_name.apply(lambda name: name in url) ].body_div.values[0] # .values return list. need str i.e. first and only element in the list
        
        content = driver.find_element(By.CSS_SELECTOR, textbody_tag)
        if (KEYWORD in content.text):
            return True
        else:
            return False
            
    except Exception as e:
        print(f"Failed: {url} -> {e}")
        return False

driver = make_driver()
keyword_check = []

try:
    for i, url in enumerate(df_goodmedia["url"]):
        if(contains_keyword(driver, str(url))):
            keyword_check.append(1)
        else:
            keyword_check.append(0)
        print(f"i = {i}, checked url {url}. result = {keyword_check[i]}.\n")
finally:
    driver.quit()

i = 0, checked url http://www.chinanews.com/mil/2018/06-30/8552129.shtml. result = 0.

i = 1, checked url http://www.xinhuanet.com/politics/2018-06/30/c_1123059151.htm. result = 0.

i = 2, checked url http://www.xinhuanet.com/politics/2018-06/30/c_1123057836.htm. result = 0.

i = 3, checked url http://hunan.voc.com.cn/article/201806/201806301027556256.html. result = 0.

i = 4, checked url http://sports.people.com.cn/worldcup2018/n1/2018/0630/c418684-30097237.html. result = 0.

i = 5, checked url http://sports.people.com.cn/worldcup2018/n1/2018/0630/c418684-30097222.html. result = 0.

Failed: http://sports.people.com.cn/worldcup2018/n1/2018/0630/c418684-30097195.html -> Message: no such element: Unable to locate element: {"method":"css selector","selector":"div.rm_txt_con.cf"}
  (Session info: chrome=151.0.7922.75); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#nosuchelementexception
Stacktrace:
0   chromedriver                        0x00000001011b9484 chromedriver + 3413124
1   chromedriver                        0x0000000100ebc2fc chromedriver + 279292
2   chromedriver                        0x0000000100f04a04 chromedriver + 576004
3   chromedriver                        0x0000000100f429b0 chromedriver + 829872
4   chromedriver                        0x0000000100efa4dc chromedriver + 533724
5   chromedriver                        0x000000010118a4cc chromedriver + 3220684
6   chromedriver                        0x000000010118d330 chromedriver + 3232560
7   chromedriver                        0x0000000101173f2c chromedriver + 3129132
8   chromedriver                        0x000000010118dc08 chromedriver + 3234824
9   chromedriver                        0x0000000101166298 chromedriver + 3072664
10  chromedriver                        0x00000001011a8d20 chromedriver + 3345696
11  chromedriver                        0x00000001011a8e80 chromedriver + 3346048
12  chromedriver                        0x00000001011b9144 chromedriver + 3412292
13  libsystem_pthread.dylib             0x0000000188aa3bc4 _pthread_start + 132
14  libsystem_pthread.dylib             0x0000000188a9eb7c thread_start + 4

i = 6, checked url http://sports.people.com.cn/worldcup2018/n1/2018/0630/c418684-30097195.html. result = 0.

i = 7, checked url http://sports.people.com.cn/n1/2018/0630/c14820-30097518.html. result = 0.

i = 8, checked url http://sports.people.com.cn/n1/2018/0630/c14820-30097513.html. result = 0.

i = 9, checked url http://www.chinanews.com/gn/2018/06-30/8552386.shtml. result = 0.

i = 10, checked url http://www.chinanews.com/ty/2018/06-30/8552478.shtml. result = 0.

i = 11, checked url http://www.xinhuanet.com/politics/2018-06/30/c_1123059799.htm. result = 0.

i = 12, checked url http://www.chinanews.com/ty/2018/07-01/8552591.shtml. result = 0.

i = 13, checked url http://sports.people.com.cn/worldcup2018/n1/2018/0701/c418684-30097951.html. result = 0.

i = 14, checked url http://sports.people.com.cn/worldcup2018/n1/2018/0701/c418684-30097917.html. result = 0.

i = 15, checked url http://sports.people.com.cn/worldcup2018/n1/2018/0701/c418684-30097876.html. result = 0.

i = 16, checked url http://www.chinanews.com/sh/2018/07-01/8552810.shtml. result = 0.

i = 17, checked url http://hunan.voc.com.cn/article/201807/201807011835441661.html. result = 0.

i = 18, checked url http://sports.people.com.cn/worldcup2018/n1/2018/0702/c418684-30099367.html. result = 0.

i = 19, checked url http://world.people.com.cn/n1/2018/0702/c1002-30098576.html. result = 0.

i = 20, checked url http://www.chinanews.com/cj/2018/07-02/8553708.shtml. result = 0.

i = 21, checked url http://www.chinanews.com/ty/2018/07-02/8553876.shtml. result = 0.

i = 22, checked url http://sports.people.com.cn/n1/2018/0703/c407727-30107184.html. result = 0.

Failed: http://sports.people.com.cn/n1/2018/0703/c14820-30106924.html -> Message: no such element: Unable to locate element: {"method":"css selector","selector":"div.rm_txt_con.cf"}
  (Session info: chrome=151.0.7922.75); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#nosuchelementexception
Stacktrace:
0   chromedriver                        0x00000001011b9484 chromedriver + 3413124
1   chromedriver                        0x0000000100ebc2fc chromedriver + 279292
2   chromedriver                        0x0000000100f04a04 chromedriver + 576004
3   chromedriver                        0x0000000100f429b0 chromedriver + 829872
4   chromedriver                        0x0000000100efa4dc chromedriver + 533724
5   chromedriver                        0x000000010118a4cc chromedriver + 3220684
6   chromedriver                        0x000000010118d330 chromedriver + 3232560
7   chromedriver                        0x0000000101173f2c chromedriver + 3129132
8   chromedriver                        0x000000010118dc08 chromedriver + 3234824
9   chromedriver                        0x0000000101166298 chromedriver + 3072664
10  chromedriver                        0x00000001011a8d20 chromedriver + 3345696
11  chromedriver                        0x00000001011a8e80 chromedriver + 3346048
12  chromedriver                        0x00000001011b9144 chromedriver + 3412292
13  libsystem_pthread.dylib             0x0000000188aa3bc4 _pthread_start + 132
14  libsystem_pthread.dylib             0x0000000188a9eb7c thread_start + 4

i = 23, checked url http://sports.people.com.cn/n1/2018/0703/c14820-30106924.html. result = 0.

i = 24, checked url http://sports.people.com.cn/n1/2018/0703/c22149-30106700.html. result = 0.

i = 25, checked url http://www.chinanews.com/ty/2018/07-03/8554613.shtml. result = 0.

i = 26, checked url http://www.chinanews.com/gn/2018/07-03/8554714.shtml. result = 0.

i = 27, checked url http://www.chinanews.com/gn/2018/07-03/8554720.shtml. result = 0.

i = 28, checked url http://www.chinanews.com/sh/2018/07-03/8554655.shtml. result = 0.

i = 29, checked url http://www.chinanews.com/ty/2018/07-03/8554917.shtml. result = 0.

i = 30, checked url http://www.chinanews.com/sh/2018/07-03/8555102.shtml. result = 1.

Failed: http://finance.people.com.cn/n1/2018/0703/c420169-30107878.html -> Message: no such element: Unable to locate element: {"method":"css selector","selector":"div.rm_txt_con.cf"}
  (Session info: chrome=151.0.7922.75); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#nosuchelementexception
Stacktrace:
0   chromedriver                        0x00000001011b9484 chromedriver + 3413124
1   chromedriver                        0x0000000100ebc2fc chromedriver + 279292
2   chromedriver                        0x0000000100f04a04 chromedriver + 576004
3   chromedriver                        0x0000000100f429b0 chromedriver + 829872
4   chromedriver                        0x0000000100efa4dc chromedriver + 533724
5   chromedriver                        0x000000010118a4cc chromedriver + 3220684
6   chromedriver                        0x000000010118d330 chromedriver + 3232560
7   chromedriver                        0x0000000101173f2c chromedriver + 3129132
8   chromedriver                        0x000000010118dc08 chromedriver + 3234824
9   chromedriver                        0x0000000101166298 chromedriver + 3072664
10  chromedriver                        0x00000001011a8d20 chromedriver + 3345696
11  chromedriver                        0x00000001011a8e80 chromedriver + 3346048
12  chromedriver                        0x00000001011b9144 chromedriver + 3412292
13  libsystem_pthread.dylib             0x0000000188aa3bc4 _pthread_start + 132
14  libsystem_pthread.dylib             0x0000000188a9eb7c thread_start + 4

i = 31, checked url http://finance.people.com.cn/n1/2018/0703/c420169-30107878.html. result = 0.

i = 32, checked url http://www.chinanews.com/gj/2018/07-04/8555928.shtml. result = 0.

i = 33, checked url http://www.chinanews.com/gj/2018/07-04/8555895.shtml. result = 0.

i = 34, checked url http://sports.people.com.cn/worldcup2018/n1/2018/0704/c418684-30126201.html. result = 0.

Failed: http://politics.people.com.cn/n1/2018/0704/c1001-30126498.html -> Message: no such element: Unable to locate element: {"method":"css selector","selector":"div.rm_txt_con.cf"}
  (Session info: chrome=151.0.7922.75); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#nosuchelementexception
Stacktrace:
0   chromedriver                        0x00000001011b9484 chromedriver + 3413124
1   chromedriver                        0x0000000100ebc2fc chromedriver + 279292
2   chromedriver                        0x0000000100f04a04 chromedriver + 576004
3   chromedriver                        0x0000000100f429b0 chromedriver + 829872
4   chromedriver                        0x0000000100efa4dc chromedriver + 533724
5   chromedriver                        0x000000010118a4cc chromedriver + 3220684
6   chromedriver                        0x000000010118d330 chromedriver + 3232560
7   chromedriver                        0x0000000101173f2c chromedriver + 3129132
8   chromedriver                        0x000000010118dc08 chromedriver + 3234824
9   chromedriver                        0x0000000101166298 chromedriver + 3072664
10  chromedriver                        0x00000001011a8d20 chromedriver + 3345696
11  chromedriver                        0x00000001011a8e80 chromedriver + 3346048
12  chromedriver                        0x00000001011b9144 chromedriver + 3412292
13  libsystem_pthread.dylib             0x0000000188aa3bc4 _pthread_start + 132
14  libsystem_pthread.dylib             0x0000000188a9eb7c thread_start + 4

i = 35, checked url http://politics.people.com.cn/n1/2018/0704/c1001-30126498.html. result = 0.

i = 36, checked url http://www.chinanews.com/gj/2018/07-05/8556789.shtml. result = 0.

i = 37, checked url http://www.chinanews.com/sh/2018/07-05/8556907.shtml. result = 0.

Failed: http://www.xinhuanet.com/local/2018-07/05/c_1123080904.htm -> Message: no such element: Unable to locate element: {"method":"css selector","selector":"div#p-detail"}
  (Session info: chrome=151.0.7922.75); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#nosuchelementexception
Stacktrace:
0   chromedriver                        0x00000001011b9484 chromedriver + 3413124
1   chromedriver                        0x0000000100ebc2fc chromedriver + 279292
2   chromedriver                        0x0000000100f04a04 chromedriver + 576004
3   chromedriver                        0x0000000100f429b0 chromedriver + 829872
4   chromedriver                        0x0000000100efa4dc chromedriver + 533724
5   chromedriver                        0x000000010118a4cc chromedriver + 3220684
6   chromedriver                        0x000000010118d330 chromedriver + 3232560
7   chromedriver                        0x0000000101173f2c chromedriver + 3129132
8   chromedriver                        0x000000010118dc08 chromedriver + 3234824
9   chromedriver                        0x0000000101166298 chromedriver + 3072664
10  chromedriver                        0x00000001011a8d20 chromedriver + 3345696
11  chromedriver                        0x00000001011a8e80 chromedriver + 3346048
12  chromedriver                        0x00000001011b9144 chromedriver + 3412292
13  libsystem_pthread.dylib             0x0000000188aa3bc4 _pthread_start + 132
14  libsystem_pthread.dylib             0x0000000188a9eb7c thread_start + 4

i = 38, checked url http://www.xinhuanet.com/local/2018-07/05/c_1123080904.htm. result = 0.

i = 39, checked url http://sports.people.com.cn/worldcup2018/n1/2018/0705/c418684-30127359.html. result = 0.

i = 40, checked url http://www.chinanews.com/sh/2018/07-05/8557398.shtml. result = 0.

i = 41, checked url http://www.chinanews.com/gn/2018/07-06/8558020.shtml. result = 0.

i = 42, checked url http://hunan.voc.com.cn/article/201807/201807060805417494.html. result = 0.

i = 43, checked url http://hunan.voc.com.cn/article/201807/201807060917148821.html. result = 0.

Failed: http://www.xinhuanet.com/local/2018-07/06/c_129908442.htm -> Message: no such element: Unable to locate element: {"method":"css selector","selector":"div#p-detail"}
  (Session info: chrome=151.0.7922.75); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#nosuchelementexception
Stacktrace:
0   chromedriver                        0x00000001011b9484 chromedriver + 3413124
1   chromedriver                        0x0000000100ebc2fc chromedriver + 279292
2   chromedriver                        0x0000000100f04a04 chromedriver + 576004
3   chromedriver                        0x0000000100f429b0 chromedriver + 829872
4   chromedriver                        0x0000000100efa4dc chromedriver + 533724
5   chromedriver                        0x000000010118a4cc chromedriver + 3220684
6   chromedriver                        0x000000010118d330 chromedriver + 3232560
7   chromedriver                        0x0000000101173f2c chromedriver + 3129132
8   chromedriver                        0x000000010118dc08 chromedriver + 3234824
9   chromedriver                        0x0000000101166298 chromedriver + 3072664
10  chromedriver                        0x00000001011a8d20 chromedriver + 3345696
11  chromedriver                        0x00000001011a8e80 chromedriver + 3346048
12  chromedriver                        0x00000001011b9144 chromedriver + 3412292
13  libsystem_pthread.dylib             0x0000000188aa3bc4 _pthread_start + 132
14  libsystem_pthread.dylib             0x0000000188a9eb7c thread_start + 4

i = 44, checked url http://www.xinhuanet.com/local/2018-07/06/c_129908442.htm. result = 0.

i = 45, checked url http://www.xinhuanet.com/politics/2018-07/07/c_1123091054.htm. result = 0.

i = 46, checked url http://www.chinanews.com/gn/2018/07-07/8559290.shtml. result = 0.

i = 47, checked url http://hunan.voc.com.cn/article/201807/201807071054273564001.html. result = 0.

i = 48, checked url http://www.xinhuanet.com/politics/2018-07/07/c_1123092757.htm. result = 0.

i = 49, checked url http://www.chinanews.com/sh/2018/07-08/8559796.shtml. result = 0.

i = 50, checked url http://www.chinanews.com/cj/2018/07-08/8559942.shtml. result = 0.

i = 51, checked url http://sports.people.com.cn/n1/2018/0709/c22155-30134403.html. result = 1.

i = 52, checked url http://sports.people.com.cn/worldcup2018/n1/2018/0709/c418684-30134115.html. result = 0.

i = 53, checked url http://www.chinanews.com/sh/2018/07-09/8560582.shtml. result = 0.

i = 54, checked url http://finance.people.com.cn/n1/2018/0709/c153577-30135902.html. result = 0.

i = 55, checked url http://sports.people.com.cn/n1/2018/0710/c22141-30136503.html. result = 0.

i = 56, checked url http://www.chinanews.com/ty/2018/07-10/8561446.shtml. result = 0.

i = 57, checked url http://www.chinanews.com/gj/2018/07-11/8562707.shtml. result = 0.

i = 58, checked url http://www.xinhuanet.com/politics/2018-07/11/c_1123107694.htm. result = 0.

i = 59, checked url http://sports.people.com.cn/worldcup2018/n1/2018/0711/c418684-30139679.html. result = 0.

i = 60, checked url http://hunan.voc.com.cn/article/201807/20180711081311465.html. result = 0.

Failed: http://www.chinanews.com/tp/hd2011/2018/07-11/828439.shtml -> Message: no such element: Unable to locate element: {"method":"css selector","selector":"div.left_zw"}
  (Session info: chrome=151.0.7922.75); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#nosuchelementexception
Stacktrace:
0   chromedriver                        0x00000001011b9484 chromedriver + 3413124
1   chromedriver                        0x0000000100ebc2fc chromedriver + 279292
2   chromedriver                        0x0000000100f04a04 chromedriver + 576004
3   chromedriver                        0x0000000100f429b0 chromedriver + 829872
4   chromedriver                        0x0000000100efa4dc chromedriver + 533724
5   chromedriver                        0x000000010118a4cc chromedriver + 3220684
6   chromedriver                        0x000000010118d330 chromedriver + 3232560
7   chromedriver                        0x0000000101173f2c chromedriver + 3129132
8   chromedriver                        0x000000010118dc08 chromedriver + 3234824
9   chromedriver                        0x0000000101166298 chromedriver + 3072664
10  chromedriver                        0x00000001011a8d20 chromedriver + 3345696
11  chromedriver                        0x00000001011a8e80 chromedriver + 3346048
12  chromedriver                        0x00000001011b9144 chromedriver + 3412292
13  libsystem_pthread.dylib             0x0000000188aa3bc4 _pthread_start + 132
14  libsystem_pthread.dylib             0x0000000188a9eb7c thread_start + 4

i = 61, checked url http://www.chinanews.com/tp/hd2011/2018/07-11/828439.shtml. result = 0.

i = 62, checked url http://www.chinanews.com/sh/2018/07-11/8563257.shtml. result = 0.

i = 63, checked url http://www.chinanews.com/ty/2018/07-11/8563195.shtml. result = 0.

Failed: http://www.xinhuanet.com/local/2018-07/11/c_1123111312.htm -> Message: no such element: Unable to locate element: {"method":"css selector","selector":"div#p-detail"}
  (Session info: chrome=151.0.7922.75); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#nosuchelementexception
Stacktrace:
0   chromedriver                        0x00000001011b9484 chromedriver + 3413124
1   chromedriver                        0x0000000100ebc2fc chromedriver + 279292
2   chromedriver                        0x0000000100f04a04 chromedriver + 576004
3   chromedriver                        0x0000000100f429b0 chromedriver + 829872
4   chromedriver                        0x0000000100efa4dc chromedriver + 533724
5   chromedriver                        0x000000010118a4cc chromedriver + 3220684
6   chromedriver                        0x000000010118d330 chromedriver + 3232560
7   chromedriver                        0x0000000101173f2c chromedriver + 3129132
8   chromedriver                        0x000000010118dc08 chromedriver + 3234824
9   chromedriver                        0x0000000101166298 chromedriver + 3072664
10  chromedriver                        0x00000001011a8d20 chromedriver + 3345696
11  chromedriver                        0x00000001011a8e80 chromedriver + 3346048
12  chromedriver                        0x00000001011b9144 chromedriver + 3412292
13  libsystem_pthread.dylib             0x0000000188aa3bc4 _pthread_start + 132
14  libsystem_pthread.dylib             0x0000000188a9eb7c thread_start + 4

i = 64, checked url http://www.xinhuanet.com/local/2018-07/11/c_1123111312.htm. result = 0.

i = 65, checked url http://politics.people.com.cn/n1/2018/0711/c420517-30141010.html. result = 0.

i = 66, checked url http://www.chinanews.com/cj/2018/07-11/8563523.shtml. result = 0.

i = 67, checked url http://www.chinanews.com/ty/2018/07-11/8563329.shtml. result = 0.

Failed: http://www.xinhuanet.com/politics/2018-07/11/c_129911853.htm -> Message: invalid session id: session deleted as the browser has closed the connection
from disconnected: Unable to receive message from renderer
  (Session info: chrome=151.0.7922.75); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalidsessionidexception
Stacktrace:
0   chromedriver                        0x00000001011b9484 chromedriver + 3413124
1   chromedriver                        0x0000000100ebc2fc chromedriver + 279292
2   chromedriver                        0x0000000100eac568 chromedriver + 214376
3   chromedriver                        0x0000000100eac288 chromedriver + 213640
4   chromedriver                        0x0000000100eaa004 chromedriver + 204804

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

In [97]:
# save keyword check result as new column in df_goodmedia. then filter to url that conatins keyword.

df_goodmedia["contains_keyword"] = keyword_check

df_filtered = df_goodmedia[ df_goodmedia.contains_keyword == 1 ]
df_filtered
df_filtered.to_csv("../data/actual_athlete_media.csv")

,title,publish_date,media_name,url,contains_keyword
33,广东中山：2020年全市将有超303个足球场,2018-07-03,chinanews.com,http://www.chinanews.com/sh/2018/07-03/8555102...,1
54,“体操皇后”霍尔金娜：在“有限”里造出个“无限”来,2018-07-09,people.com.cn,http://sports.people.com.cn/n1/2018/0709/c2215...,1

In [99]:
# clickable 
df_filtered.url.values

array(['http://www.chinanews.com/sh/2018/07-03/8555102.shtml',
       'http://sports.people.com.cn/n1/2018/0709/c22155-30134403.html'],
      dtype=object)